[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log
autorestart=true

[program:api]
command=python api_runner.py
directory=/app
stdout_logfile=/var/log/supervisor/api.log
stderr_logfile=/var/log/supervisor/api.log
autorestart=true
environment=MQTT_BROKER_HOST="%(ENV_MQTT_BROKER_HOST)s",MQTT_BROKER_PORT="%(ENV_MQTT_BROKER_PORT)s",API_HOST="0.0.0.0",API_PORT="8000"

[program:simulator]
command=python simulator_runner.py
directory=/app
stdout_logfile=/var/log/supervisor/simulator.log
stderr_logfile=/var/log/supervisor/simulator.log
autorestart=true
environment=MQTT_BROKER_HOST="%(ENV_MQTT_BROKER_HOST)s",MQTT_BROKER_PORT="%(ENV_MQTT_BROKER_PORT)s"
