services:
  # MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: homegenie-mqtt
    ports:
      - "1883:1883"
      - "9003:9001"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mqtt-data:/mosquitto/data
      - mqtt-logs:/mosquitto/log
    networks:
      - homegenie-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "test"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HomeGenie Unified Application
  homegenie:
    build:
      context: .
      dockerfile: Dockerfile.unified
    container_name: homegenie-app
    ports:
      - "8080:8000"   # API
      - "3000:3000"   # Web UI
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      mqtt-broker:
        condition: service_healthy
    networks:
      - homegenie-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs

networks:
  homegenie-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mqtt-data:
  mqtt-logs: