
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '29ada689f6dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Write your upgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contextsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    """Write your downgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contextsnapshot')
    # ### end Alembic commands ###
